title:             Youngjoon Oh
email:             youngjoon@qti.qualcomm.com
description:       Software Engineer at Qualcomm AI Research
author:            Youngjoon Oh
baseurl:           "/"
url:               "https://oyj0594.github.io"



# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

theme: jekyll-theme-cayman
