title:             Youngjune Oh
email:             youngjune@popeye.snu.ac.kr
description:       M.S Candidate at Seoul Nat'l University
author:            Youngjune Oh
baseurl:           "/"
url:               "https://oyj0594.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   oyj0594
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

theme: jekyll-theme-cayman
